### ISSUE TITLE
The way to specify the order of derivatives is still too complicated...

### ISSUE THREAD

**Issue by zhiyuanzhai** [sjelatex/derivative#10]
For example, to type a simple second-order partial derivative
$$\frac{\partial^2 f}{\partial x^2},$$
it still requires an explicit claim of the key `order`:
```latex
\pdv[order=2]{f}{x}
```
which is quite annoying, given how frequently it is to encounter such second-order derivatives.

It would be more convenient if it is possible to omit the key `order` and just put down something like
```latex
\pdv[2]{f}{x}
```

**Comment by sjelatex** [comment]
I agree with this, But I have looked into this for a while now, but there isn't really a good way to make it work for all cases with the current implementation. See #2 for a similar question.

However, today I noticed a new pre-processor `={<text>}` in ltcmd (formerly known as xparse). It pre-proces an argument and check for a key-value syntax, and if it does not find a key-valye syntax then insert `<text>=` in front of the argument.

I actually think this will solve the issue, because the current implementation of the derivative arguments is
```
...
\exp_args:Nne #1 {#3}{ s o m t/ t! m !e{\char_generate:nn {`_}{8}^} }
...
```
which have to be changed to
```
...
\exp_args:Nne #1 {#3}{ s ={order}o m t/ t! m !e{\char_generate:nn {`_}{8}^} }
...
```
So that `\pdv[2]{f}{x}` is pre-processed internally as `\pdv[order={2}]{f}{x}`, while `\pdv[sep-inf-var=2]{f}{x}` is pre-processed internally as `\pdv[sep-inf-var=2]{f}{x}`.

I will finish writing the documentation for version 1.3 and release (within a week, hopefully) and then look into this a bit more.

**Comment by amilkyboi** [comment]
Just chiming in to show my support for implicit ordering. Quickly looking into other packages, I noticed that `diffcoeff`, `commath`, and `esdiff` all have implicit ordering as standard. Is there a reason that the backend used by these packages can't be co-opted? Granted, I know nothing of how packages are implemented, just something I noticed when looking around.

I ask primarily because I enjoy the macro structure and other features of this package, but having to write `order=n` all the time really does get old. Hope to see some updates on this in the future!

**Comment by sjelatex** [comment]
I have carefully considered how to implement this feature for a while now. I have two potential solution to address this request for implicit order. Since I haven't written any documents with mathematics or physics for a few years now, I'm not really certain how any of my proposed solutions feels in practice.

The idea with the current key-value implementation, is to give high flexibility to tweak the display of each derivative. It came with the cost of having to write `order=...` to set the order. I do get this is cumbersome in length, most likely because it is the only key used in most cases.



#### Solution 1: The `unknown` key

This approach involves introducing the unknown key, which handles undefined keys, specifically orders without the order= specifier. The unknown key is then used to contribute to the order sequence. Figure 1 illustrates the results of this approach.

Implementing by adding the below to `\cs_new:Npn \__deriv_dv_define_keys:n #1`
```
unknown .code:n =
{
	\bool_if:NT \l__deriv_first_unknown_key_bool
	{ % The clist contains 1, so remove it at first unknown key.
		\clist_clear:c { l__deriv_dv_#1_misc_order_clist }
		\bool_set_false:N \l__deriv_first_unknown_key_bool
	}
	% Rescan because keys are strings not token list!
	% Add to the list of orders after
	\exp_args:NnnV \tl_set_rescan:Nnn \l__deriv_tmpa_tl {} \l_keys_key_str
	\clist_put_right:cV { l__deriv_dv_#1_misc_order_clist } \l__deriv_tmpa_tl
}
```
and
```
\cs_new_protected:Npn \deriv_local_keys:nnn #1 #2 #3
{
	\bool_set_true:N \l__deriv_first_unknown_key_bool
	...
```

Figure 1:
![image](https://github.com/sjelatex/derivative/assets/68080512/6e4abbc5-2a22-4222-92de-69c640b715b4)

#### Solution 2: The pre-processor `={order}`

As mentioned earlier, another solution involves leveraging the new pre-processor in ltcmd. This key, denoted as `={order}`, aims to preprocess arguments and insert `order=` in front of the argument when a key-value syntax is not detected. Figure 2 illustrates the results of this approach. Please note that the last row in the code produces errors.

```
...
\exp_args:Nne #1 {#3}{ s ={order}o m t/ t! m !e{\char_generate:nn {`_}{8}^} }
...
```

Figure 2:
![image](https://github.com/sjelatex/derivative/assets/68080512/d04aea36-7ec6-47b8-87ba-5f492f92e2c9)


I used the code below to produce the figure for both solutions.
```
\documentclass{scrartcl}
\usepackage{derivative}
\usepackage{amsmath}
\begin{document}
	\begin{align}
		\pdv[order=2]{f}{x} && \pdv[2]{f}{x} \\
		\pdv[order=\alpha]{f}{x} && \pdv[\alpha]{f}{x} \\
		\pdv[order={2,a}]{f}{x,y,z} && \pdv[2,a]{f}{x,y,z} \\
		\pdv[switch-*=true]{f}{x,y,z} && \pdv[switch-*]{f}{x,y,z} \\
		\pdv[switch-*=true, order={2,a}]{f}{x,y,z} && \pdv[switch-*, order={2,a}]{f}{x,y,z} \\
		\pdv[2+n, \beta, switch-*=true]{f}{x,y,z} && \pdv[2+n, switch-*=true, \beta]{f}{x,y,z}
	\end{align}
\end{document}
```
