### ISSUE TITLE
Implict order parameter

### ISSUE THREAD

**Issue by orsonhart** [sjelatex/derivative#2]
I'm wanting to use the derivative package instead of the physics package for derivatives.
In the physics package I'm used to `\pdv[n]{y}{x}` but now in the derivative package I have to type `\pdv[order=n]{y}{x} ` which is slower to type, and less readable.

Thoughts on a package option for having an optional parameter with no parameter specified default to the `order` parameter?

**Comment by sjelatex** [comment]
There have been a few people requesting feature, so I'm currently looking into it. Back when I changed the order argument into a key-value, I thought of a way to handle the scenario you seek. After some testing it does work, however there are some errors regarding my implementation of it that is beyond my control.

I thought of using the `unknown` key from the `l3keys` module to handle it. Say we wrote `\pdv[n]{y}{x}` then `n` would be an unknown key, because I haven't defined an option with this name. Then the `unknown` key will grab the `n` and I can set it equal to the order. But the problem it, `l3keys` converts all keys into `strings` by changing catcodes (i.e. it uses `\detokenize`). This is a major issues for this to work properly in all cases.
Reason is:
It can handle things like `\odv[n]{y}{x}`, `\odv[2]{y}{x}` and `\odv[n+2]{y}{x}` etc. But if were to write `\odv[\alpha]{y}{x}`, then It would convert to `\frac{ d^\alpha y}{ d x^\alpha }`, but with `\alpha` being written literally as `\alpha` and not the greek letter alpha (see below)

<img width="152" alt="image" src="https://user-images.githubusercontent.com/68080512/182013318-5aa1c19b-1b74-4a34-8c8a-e6315be7fd4c.png">
