### ISSUE TITLE
Different Symbols for Numerator and Denominator

### ISSUE THREAD

**Issue by romain-noel** [sjelatex/derivative#3]
I think another option/setting that deserves to be added is the possibility to have different symbols for numerators and denominators.
Such option exists in `diffcoeff` package and is convenient for some mathematical and physical equations that I use.

For example, the LHS could yield the RHS in the following command:	

    \pdv[style-inf=\nabla, style-inf-denom=d]{f}{t}= \frac{\nabla f}{d t}

The same thing can be done with `diffcoeff` package it can be done thanks to:

	\diffdef{d2}{
	  op-symbol = \nabla,
	  op-symbol-alt = d
	  }
	\begin{equation}
	  \diff.d2.{f}{t}
	\end{equation}

And it can be kept that by default `style-inf` is equal to `style-inf-denom` (or another name) if the latter is not given.

**Comment by sjelatex** [comment]
This shouldn't be much of an issue to implement.

**Comment by sjelatex** [comment]
Implemented the feature and seems to work fine. Will be uploaded sometime in the future.

<img width="213" alt="image" src="https://user-images.githubusercontent.com/68080512/184504299-f6e876df-1f31-4e88-8b41-9924e9ea027a.png">

Note that `\qdv` will not be added in the next release.
Still need to do some more testing of the fractional calculus calculator for mixed order. Probably also added some of the other requested features. Update documentation....

**Comment by romain-noel** [comment]
Sorry I missed your comment (mail box synchronization issue from my side, oups).

I seems great. 

I made a pull request (#5 related to #1).
However, this pull request does not take into account improvements you are showing here ;  and I think it will need a bit of extra work to make compatible (and treat combination cases), but nothing too hard.
Therefore, do not hesitated to give me access to your recent modification (on a separated branch or any other way you see), so I can work on this compatibility.

**Comment by DoktorScience** [comment]
Hello, I would also be interested in this feature. In the literature, you sometimes encounter derivatives typeset like the following

```latex
\frac{\mathrm{d}_s f}{\mathrm{d}}
```

in order to denote the convective derivative when multiple "species" are found e.g. in a fluid.
Would you consider an update / help with this contribution soon?

Many thanks!

**Comment by sjelatex** [comment]
> Hello, I would also be interested in this feature. In the literature, you sometimes encounter derivatives typeset like the following
> 
> ```
> \frac{\mathrm{d}_s f}{\mathrm{d}}
> ```
> 
> in order to denote the convective derivative when multiple "species" are found e.g. in a fluid. Would you consider an update / help with this contribution soon?
> 
> Many thanks!

The code is already in [version 2 draft](https://github.com/sjelatex/derivative/tree/version2-draft). You can download it and use it in your documents. I haven't written the documentation of the the new features yet, because I thought of a new feature I wanted to implement. But it takes longer than expected. In this version we have
```
style-inf = d,       % Sets the numerator operator symbol
style-inf-denom = d, % Sets the denominator operator symbol
```
If you want to create a new derivative you can do
`\NewDerivative{\mydv}{d}[style_inf = d_s]`
or
`\NewDerivative{\mydv}{d_s}[style_inf-denom = d]`
If you rather want to edit an existing derivative
`\derivset{\odv}[style_inf = d_s]`

**Comment by DoktorScience** [comment]
Thank you both very much for your clarifications, looking forward to v2!
